# Generated by Django 5.0.3 on 2024-03-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('std_number', models.CharField(max_length=9)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('age', models.PositiveIntegerField()),
                ('departement', models.CharField(choices=[('cs', 'cs'), ('it', 'it ')], default='cs', max_length=50)),
            ],
        ),
    ]
