# Generated by Django 5.0.3 on 2024-03-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0002_person_rename_departement_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(choices=[('cs', 'cs'), ('it', 'it ')], default='cs', max_length=50),
        ),
    ]
