# Generated by Django 5.0.3 on 2024-03-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0003_person_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='date',
            new_name='pdate',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='department',
            new_name='pdepartment',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='pname',
        ),
    ]
